language: rust
rust: nightly
before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/terry_guo-gcc-arm-embedded-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
    - sudo apt-get install gcc-arm-none-eabi
script:
    - cargo build --target=thumbv7m-none-eabi --release
