[package]
name = "tockfridge"
version = "0.1.0"
authors = ["Felix Obenhuber <felix.obenhuber@esrlabs.com>"]

[dependencies]
tock = { path = "../libtock-rs" }

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true
